name: SATUTS-CI

on:
  push:
    branches: ["main", "desarrollo"]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.x
      - name: Create .env file
        run: |
          echo APP_ENVIRONMENT = ${{ secrets.APP_ENVIRONMENT }} >> .env
          echo ALLOWED_ORIGIN = ${{ secrets.ALLOWED_ORIGIN }} >> .env
          echo DB_HOST = ${{ secrets.DB_HOST }} >> .env
          echo DB_PORT = ${{ secrets.DB_PORT }} >> .env
          echo DB_USER = ${{ secrets.DB_USER }} >> .env
          echo DB_PASSWORD = ${{ secrets.DB_PASSWORD }} >> .env
          echo DB_NAME = ${{ secrets.DB_NAME }} >> .env
          echo JWT_SECRET = ${{ secrets.JWT_SECRET }} >> .env
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:e2e
      - name: Deploy to Render
        env:
          RENDER_SERVICE_ID: ${{ secrets.ONRENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.ONRENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY"
